<?php
/**
 * @file
 * Code for the TPS Discussion feature.
 */

include_once 'tps_discussion.features.inc';

/**
 * @file
 * TPS Discussion module.
 */

/**
 * Implements hook_default_rules_configuration_alter().
 *
 * Remove OG's default notification Rules, as this modules has a superior
 * version of it, that uses Message notify.
 *
 * @see og_example_default_rules_configuration_alter()
 */
function tps_discussion_default_rules_configuration_alter(&$configs) {
  if (isset($configs['rules_og_new_content'])) {
    unset($configs['rules_og_new_content']);
  }
}
