<?php

/**
 * @file
 * TPS UX module installation and updates.
 */

/**
 * Disable plain_text after it's no longer the fallback.
 *
 * This is the lightest way to remove the confusing option for users to post in
 * plain text.
 */
function tps_ux_update_7000() {
  // @see filter_fallback_format().
  variable_set('filter_fallback_format', 'filtered_html');
  // Now we can safely disable plain text format.
  filter_format_disable('plain_text');
}
